apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubedemo
  namespace: flux-system
  labels:
    managed.syn.servicenow.com/name: kubedemo-supervisor
    managed.syn.servicenow.com/namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: hello
  timeout: 60s
  url: https://github.com/bhargu99/kubedemo
